[tools]
luau-lsp = "JohnnyMorganz/luau-lsp@1.40.0"
rojo ="rojo-rbx/rojo@7.4.4"
selene = "Kampfkarren/selene@0.28.0"
stylua = "johnnymorganz/stylua@2.0.2"
wally = "UpliftGames/wally@0.3.2"
wally-package-types = "JohnnyMorganz/wally-package-types@1.4.2"
