[package]
name = "dig1t/ragdoll"
version = "1.0.4"
description = "Module part of the dig1t/roblox-modules repository. Find the API here: https://dig1t.github.io/roblox-modules/api/Ragdoll"
license = "Apache-2.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["*.spec.luau"]

[dependencies]
Util = "dig1t/util@1.0.17"
